# Generated by Django 5.2.8 on 2025-11-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='meal_choice',
            field=models.CharField(choices=[('STANDARD', 'Standard'), ('VEGETARIEN', 'Végétarien'), ('VEGAN', 'Vegan'), ('SANS_GLUTEN', 'Sans gluten'), ('ENFANT', 'Enfant')], default='STANDARD', max_length=20, verbose_name='Choix du plat'),
        ),
    ]
