# Generated by Django 5.2.8 on 2025-11-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_meal_remove_booking_meal_choice_booking_meal'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description de la réservation'),
        ),
    ]
