# Generated by Django 5.2.8 on 2025-11-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_booking_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Prix (€)'),
        ),
    ]
